spring:
  application.name: search
  jmx.enabled: false
#  kafka:
#    bootstrap-servers: localhost:9093

server.port: 10002

elastic.host: https://${ES_ADDRESS}
elastic.port: 9200
booksUrl: http://${STORAGE_ADDRESS}:10001/api/books/

eureka:
  instance:
    hostname: search
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_ADDRESS}:8761/eureka/

management.endpoints.web.exposure.include: '*'
