AWSTemplateFormatVersion: '2010-09-09'
Description: Main stack containing links to S3 buckets with other stacks
Resources:
  SecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://aws-course-templates.s3-us-west-2.amazonaws.com/SecurityGroup.yml
      TimeoutInMinutes: '15'
  IAMRoleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://aws-course-templates.s3-us-west-2.amazonaws.com/Role.yml
      TimeoutInMinutes: '15'
  ElasticsearchStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - IAMRoleStack
    Properties:
      TemplateURL: https://aws-course-templates.s3-us-west-2.amazonaws.com/ElasticSearch.yml
      TimeoutInMinutes: '20'
      Parameters:
        IAMRoleArn: {"Fn::GetAtt": ["IAMRoleStack","Outputs.IAMRoleArn"]}
  DynamoDBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://aws-course-templates.s3-us-west-2.amazonaws.com/DynamoDB.yml
      TimeoutInMinutes: '15'
  SQSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://aws-course-templates.s3-us-west-2.amazonaws.com/SQS.yml
      TimeoutInMinutes: '15'
  EC2EurekaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - ElasticsearchStack
      - DynamoDBStack
      - SQSStack
      - SecurityGroupStack
    Properties:
      TemplateURL: https://aws-course-templates.s3-us-west-2.amazonaws.com/EC2Eureka.yml
      TimeoutInMinutes: '15'
      Parameters:
        SecurityGroupId: {"Fn::GetAtt": ["SecurityGroupStack","Outputs.SecurityGroupID"]}
  EC2StorageStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - EC2EurekaStack
    Properties:
      TemplateURL: https://aws-course-templates.s3-us-west-2.amazonaws.com/EC2Storage.yml
      TimeoutInMinutes: '15'
      Parameters:
        EurekaAddress: {"Fn::GetAtt": ["EC2EurekaStack","Outputs.EurekaAddress"]}
        SecurityGroupId: {"Fn::GetAtt": ["SecurityGroupStack","Outputs.SecurityGroupID"]}
  EC2SearchStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - EC2StorageStack
    Properties:
      TemplateURL: https://aws-course-templates.s3-us-west-2.amazonaws.com/EC2Search.yml
      TimeoutInMinutes: '15'
      Parameters:
        EurekaAddress: {"Fn::GetAtt": ["EC2EurekaStack","Outputs.EurekaAddress"]}
        ElasticEndpoint: {"Fn::GetAtt": ["ElasticsearchStack","Outputs.ElasticAddress"]}
        StorageAddress: {"Fn::GetAtt": ["EC2StorageStack","Outputs.StorageAddress"]}
        SecurityGroupId: {"Fn::GetAtt": ["SecurityGroupStack","Outputs.SecurityGroupID"]}