AWSTemplateFormatVersion: 2010-09-09
Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows outbound for all addresses and inbound from EPAM SPb network
      VpcId: vpc-9f0196e7
      SecurityGroupIngress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
Outputs:
  SecurityGroupID:
    Description: The id of security group
    Value: {"Fn::GetAtt": ["InstanceSecurityGroup","GroupId"]}